version: "3.8"

services:

  mariadb:
    image: mariadb
    container_name: mariadb
  #   networks:
  #     - inception
    build:
      context: requirements/mariadb/.
      dockerfile: Dockerfile
  # #   env_file:
  # #     - .env
    # volumes:
    #    - mariadb:/var/lib/mysql
  #   restart: unless-stopped
    expose:
      - "3306"

  # wordpress:
  #   image: wordpress
  #   container_name: wordpress
  #   networks:
  #     - inception
  #   build:
  #     context: requirements/wordpress/.
  #     dockerfile: Dockerfile
  #   env_file: .env
  #   volumes:
  #     - wordpress:/var/www/html
  #   restart: unless-stopped
  #   depends_on:
  #     - mariadb
  #   expose:
  #     - "80"

  nginx:
    image : nginx
    container_name: nginx
    # networks :
    #   - inception
    build:
      context: requirements/nginx/.
      dockerfile: Dockerfile
    # env_file:
    #   - .env
    volumes:
      - ./web:/var/www/wordpress
    # restart: unless-stopped
    # depends_on:
    #   - wordpress
    ports:
      - "443:443"

  # volumes:
  #   mariadb:
  #     driver: local
  #   wordpress:
  #     driver: local

  # networks:
  #   inception:
  #     driver: bridge