CREATE DATABASE IF NOT EXISTS '$SQL_DATABASE';
CREATE USER IF NOT EXISTS '$SQL_USER'@'%' IDENTIFIED BY '$SQL_PASSWORD';
GRANT ALL PRIVILEGES ON '$SQL_DATABASE.*' TO '$SQL_USER'@'%' IDENTIFIED BY '$SQL_PASSWORD' WITH GRANT OPTION;
FLUSH PRIVILEGES;